# Jekyll configuration
title: lynn's house
author: Lynn
description: look!! a strange bug
url: https://lynn.github.io

# Build settings
markdown: kramdown
permalink: /blog/:title/

include: [".well-known"]

# Exclude files from processing
exclude:
  - README.md
  - readme.txt
